import { ALL_PROGRAMS } from '../../src/phase5/programs';
import { assembleRv, bytesToHex, runToHalt } from './golden';

/** Source text of src/phase5/programs.data.ts, computed with packages/asm and packages/rv32. */
export function programsDataSource(): string {
  const rows = ALL_PROGRAMS.map((p) => {
    const bytes = assembleRv(p.source);
    const s = runToHalt(bytes);
    return `  '${p.name}': { hex: '${bytesToHex(bytes)}', a0: 0x${s.x[10]!.toString(16)}, steps: ${s.steps} },`;
  });
  return `// GENERATED by solutions/phase5/gen-data.ts from programs.ts: do not edit.
// Regenerate with UPDATE_RV_PROGRAMS=1 npx vitest run src/phase5 (in packages/content).

/** Assembled bytes (linked at 0), a0 at ebreak and instructions executed, per program (packages/asm + packages/rv32). */
export const RV_PROGRAM_DATA: Record<string, { hex: string; a0: number; steps: number }> = {
${rows.join('\n')}
};
`;
}
