/**
 * Generates os.data.ts (and ../../solutions/phase9/solutions.data.ts) from
 * @build-a-computer/os-kit: each level's library files, starter, solution,
 * test disks and the numbers expected output depends on. Test-only (node):
 * phase9.test.ts checks the committed files are current and rewrites them
 * with UPDATE_OS_DATA=1.
 */

import { createHash } from 'node:crypto';
import { LEVEL_KEYS, type LevelKey, buildKit, diskSetup } from '@build-a-computer/os-kit';
import { SNAKE_CASES, snakeModel } from './snake';

/** Level id for each os-kit level. */
export const LEVEL_IDS: Record<LevelKey, string> = {
  boot: 'os-bootloader',
  trap: 'os-trap-vector',
  syscall: 'os-system-calls',
  proc: 'os-context-switch',
  timer: 'os-preemption',
  vm: 'os-virtual-memory',
  alloc: 'os-page-allocator',
  fs: 'os-file-system',
  shell: 'os-shell',
  game: 'os-final-game',
};

const HEADER = (what: string) =>
  `// GENERATED by src/phase9/gen-data.ts from packages/os-kit: do not edit.\n` +
  `// Regenerate with UPDATE_OS_DATA=1 npx vitest run src/phase9 (in packages/content).\n\n/** ${what} */\n`;

const q = (s: string): string => JSON.stringify(s);

export interface Generated {
  data: string;
  solutions: string;
}

export function generate(): Generated {
  const kits = LEVEL_KEYS.map((k) => buildKit(k));
  const out: string[] = [
    HEADER('Phase 9 level kits: library files, starter, test disks and facts (packages/os-kit).'),
    'export interface OsDisk {\n  sector: number;\n  hex: string;\n}\n',
    "export interface OsKitData {\n  language: 'c' | 'rv32-asm';\n  starter: string;\n  library: { name: string; text: string }[];\n  disks: Record<string, OsDisk[]>;\n  sizes: Record<string, number>;\n  facts: Record<string, number>;\n}\n",
    'export const OS_DATA: Record<string, OsKitData> = {',
  ];
  for (const kit of kits) {
    out.push(`  ${q(LEVEL_IDS[kit.key])}: {`);
    out.push(`    language: ${q(kit.language)},`);
    out.push(`    starter: ${q(kit.starter)},`);
    out.push('    library: [');
    for (const f of kit.library) out.push(`      { name: ${q(f.name)}, text: ${q(f.text)} },`);
    out.push('    ],');
    out.push('    disks: {');
    for (const [name, disk] of Object.entries(kit.disks)) {
      out.push(`      ${q(name)}: [`);
      for (const d of diskSetup(disk))
        out.push(`        { sector: ${d.sector}, hex: ${q(d.hex)} },`);
      out.push('      ],');
    }
    out.push('    },');
    out.push(`    sizes: ${JSON.stringify(kit.sizes)},`);
    out.push(`    facts: ${JSON.stringify(kit.facts)},`);
    out.push('  },');
  }
  out.push('};\n');
  out.push('/** SHA-256 of the framebuffer the snake model draws, by test name (snake.ts). */');
  out.push('export const SNAKE_SHA256: Record<string, string> = {');
  for (const c of SNAKE_CASES)
    out.push(
      `  ${q(c.name)}: ${q(createHash('sha256').update(snakeModel(c.keys).pixels).digest('hex'))},`,
    );
  out.push('};\n');

  const sol: string[] = [
    HEADER(
      "Reference solutions (the player's main.c / main.s) for the Phase 9 levels, by level id.",
    ),
    'export const PHASE9_SOLUTIONS: Record<string, string> = {',
  ];
  for (const kit of kits) sol.push(`  ${q(LEVEL_IDS[kit.key])}: ${q(kit.solution)},`);
  sol.push('};\n');
  return { data: out.join('\n'), solutions: sol.join('\n') };
}
