/**
 * Generates catalog.data.ts from the full levels. Test-only (node):
 * catalog.test.ts checks the committed file is current and rewrites it with
 * UPDATE_CATALOG=1.
 */
import type { Level } from '@build-a-computer/schema';
import type { LevelGroup, LevelInfo } from './catalog';
import { LEVELS } from './full';
import { SANDBOX } from './sandbox';
import { PHASE0_2_LEVELS } from './phase0-2';
import { PHASE3_4_LEVELS } from './phase3-4';
import { PHASE5_LEVELS } from './phase5';
import { PHASE6_LEVELS } from './phase6';
import { PHASE7_LEVELS } from './phase7';
import { PHASE8_LEVELS } from './phase8';
import { PHASE9_LEVELS } from './phase9';
import { TRACK2_P1_3_LEVELS } from './track2/phase1-3';
import { TRACK2_P4_7_LEVELS } from './track2/phase4-7';

const GROUP_LEVELS: Record<LevelGroup, readonly Level[]> = {
  sandbox: [SANDBOX],
  'phase0-2': PHASE0_2_LEVELS,
  'phase3-4': PHASE3_4_LEVELS,
  phase5: PHASE5_LEVELS,
  phase6: PHASE6_LEVELS,
  phase7: PHASE7_LEVELS,
  phase8: PHASE8_LEVELS,
  phase9: PHASE9_LEVELS,
  'track2-1-3': TRACK2_P1_3_LEVELS,
  'track2-4-7': TRACK2_P4_7_LEVELS,
};

export function catalogEntry(l: Level, group: LevelGroup): LevelInfo {
  return {
    id: l.id,
    version: l.version,
    track: l.track,
    phase: l.phase,
    order: l.order,
    title: l.title,
    goal: l.goal,
    palette: l.palette,
    requires: l.requires,
    mode: l.mode,
    optional: l.optional,
    draft: l.draft,
    hintCount: l.hints.length,
    group,
  };
}

/** The catalog, in LEVELS order. */
export function catalog(): LevelInfo[] {
  const groupOf = new Map<string, LevelGroup>();
  for (const [g, levels] of Object.entries(GROUP_LEVELS) as [LevelGroup, readonly Level[]][])
    for (const l of levels) groupOf.set(l.id, g);
  return LEVELS.map((l) => {
    const g = groupOf.get(l.id);
    if (!g) throw new Error(`Level ${l.id} is in no group`);
    return catalogEntry(l, g);
  });
}

export function catalogSource(): string {
  return (
    `// GENERATED by src/gen-catalog.ts from the full levels: do not edit.\n` +
    `// Regenerate with UPDATE_CATALOG=1 npx vitest run src/catalog.test.ts (in packages/content).\n\n` +
    `import type { LevelInfo } from './catalog';\n\n` +
    `/** The light level catalog (see catalog.ts). */\n` +
    `export const CATALOG: LevelInfo[] = [\n` +
    catalog()
      .map((e) => `  ${JSON.stringify(e)},\n`)
      .join('') +
    `];\n`
  );
}
