/* Generated by scripts/fuzz.mjs --kind=struct (seed 26). */
#include "prelude.h"
struct S0 { int f0 : 10; short f1; };
struct S1 { char f0; char f1; unsigned long long f2; unsigned char f3; };
static unsigned long long v1 = (unsigned long long)1484018199LL * 350616204LL;
static short a7[5] = { (short)9, (short)1585855669 };
static struct S0 s10 = { (-510126056), 15 };
static struct S0 s11 = { (-115), 1222178299 };
static struct S1 bump(struct S1 x, int k) { x.f0 += (char)k; return x; }
static long total(const long *p, int n) { long s = 0; int i; for (i = 0; i < n; i++) s ^= (long)(p[i] + (long)i); return s; }
static long tz_[4] = { 1, 2, 3, 4 };
int main(void) {
  signed char v0 = (signed char)14;
  long v2 = (long)7;
  short v3 = (short)(-187);
  unsigned v4 = (unsigned)2107428483;
  unsigned long long v5 = (unsigned long long)(-920453620);
  char a6[8] = { 0 };
  short a8[4] = { (short)7, (short)7 };
  struct S1 s9 = { 18032295, 3, 8, 360966264 };
  struct S1 *p12 = &s9;
  struct S0 *p13 = &s10;
  /* bump: struct by value */
  s10.f1 = (short)(p12->f0 & (bump(s9, 5).f0 ? (p12->f3 | s9.f2) : (s9.f2 ? s9.f2 : p12->f3)));
  s9.f2 = (unsigned long long)p12->f2;
  s10.f0 = (int)((short)1708820078);
  s9.f1 = (char)((int)((unsigned)(((s11.f1) == 0 || ((v0) == (-2147483647 - 1) && (s11.f1) == -1)) ? (int)(v0) : (int)(v0 % s11.f1)) << ((v3) & 31)));
  if (s11.f0) { s10.f1 = (short)s9.f3; } else { switch ((unsigned)(((int)((unsigned)v0 - (unsigned)((short)10)))) % 5u) { case 0: v4 = (unsigned)v4; break; case 1: s11 = s10; break; case 2: { int i14; for (i14 = 0; i14 < 4; i14++) { a7[(unsigned)((((((long long)63263010LL * 365146002LL)) == 0 || ((((int)6)) == (-9223372036854775807LL - 1) && (((long long)63263010LL * 365146002LL)) == -1)) ? (long long)(((int)6)) : (long long)(((int)6) % ((long long)63263010LL * 365146002LL)))) % 5u] = (short)(((((s9.f0 | ((unsigned short)806060380))) == 0) ? (unsigned)((s10.f1 + v4)) : (unsigned)((s10.f1 + v4) % (s9.f0 | ((unsigned short)806060380)))) && a7[(unsigned)(((int)((unsigned)a8[(unsigned)(((int)((unsigned)s11.f0 + (unsigned)s11.f0))) % 4u] + (unsigned)s9.f1))) % 5u]);  s9.f0 = (char)(((unsigned)((unsigned)((unsigned)(-1624261370)) << ((((int)((unsigned)p12->f3 << ((s10.f1) & 31)))) & 31))) ? ((int)((unsigned)(s10.f1 > s10.f1) << ((((int)((unsigned)s11.f1 - (unsigned)p13->f1))) & 31))) : ((long long)(p12->f0 >> ((s9.f2) & 31)))); } }  default: a6[(unsigned)(bump(s9, 8).f0) % 8u] = (char)(((unsigned char)a8[(unsigned)((a7[(unsigned)(s11.f1) % 5u] || ((short)(-1456790788)))) % 4u]) + (v4 + ((char)(-111)))); } }
  { int k_; for (k_ = 0; k_ < 4; k_++) mix((unsigned)(a8[k_])); }
  s11.f0 = (int)(((_Bool)v1) | ((long)p12->f0));
  if (s9.f2) { s11.f0 = (int)((short)(((v4) == 0) ? (unsigned)(((char)(-1625353074))) : (unsigned)(((char)(-1625353074)) % v4))); } else { v2 = (long)(p13->f0 < ((int)((unsigned)v0 + (unsigned)p12->f3))); }
  { int i15; for (i15 = 0; i15 < 1; i15++) { { int i16; for (i16 = 0; i16 < 2; i16++) { s9 = s9; if ((p12->f1) & 1) continue; { int i17; for (i17 = 0; i17 < 2; i17++) { s10.f0 = (int)((int)((unsigned)((int)((unsigned)a6[(unsigned)((((long)12) || v5)) % 8u] << ((v1) & 31))) * (unsigned)(s9.f1 | s11.f1)));  v2 = (long)((((((int)((unsigned)((char)(-87271067)) - (unsigned)s11.f0))) == 0 || ((((signed char)((char)1407860726))) == (-2147483647 - 1) && (((int)((unsigned)((char)(-87271067)) - (unsigned)s11.f0))) == -1)) ? (int)(((signed char)((char)1407860726))) : (int)(((signed char)((char)1407860726)) / ((int)((unsigned)((char)(-87271067)) - (unsigned)s11.f0)))) ^ v0); } } } } if ((((int)907447785)) & 1) continue; { int i18; for (i18 = 0; i18 < 3; i18++) { { int i19; for (i19 = 0; i19 < 3; i19++) { v2 = (long)p12->f0;  s9.f3 = (unsigned char)(((a6[(unsigned)(v5) % 8u]) == 0 || ((((a8[(unsigned)((a8[(unsigned)(s9.f2) % 4u] ? s11.f1 : a8[(unsigned)(a7[(unsigned)(p13->f1) % 5u]) % 4u])) % 4u] & s9.f1) & s10.f0)) == (-2147483647 - 1) && (a6[(unsigned)(v5) % 8u]) == -1)) ? (int)(((a8[(unsigned)((a8[(unsigned)(s9.f2) % 4u] ? s11.f1 : a8[(unsigned)(a7[(unsigned)(p13->f1) % 5u]) % 4u])) % 4u] & s9.f1) & s10.f0)) : (int)(((a8[(unsigned)((a8[(unsigned)(s9.f2) % 4u] ? s11.f1 : a8[(unsigned)(a7[(unsigned)(p13->f1) % 5u]) % 4u])) % 4u] & s9.f1) & s10.f0) / a6[(unsigned)(v5) % 8u])); } }  { int i20; for (i20 = 0; i20 < 4; i20++) { p13->f0 = (int)(total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4) ? s11.f0 : ((p12->f0 >> ((p12->f2) & 31)) && (s9.f2 > p12->f0)));  v1 = (unsigned long long)(v3 ^ ((p12->f2 & a7[(unsigned)((v0 | v2)) % 5u]) - ((unsigned)(-433650975)))); } } } } } }
  { int w21 = 2; do { switch ((unsigned)(v3) % 5u) { case 0: { int w22 = 3; do { s11.f1 = (short)p13->f0; } while (--w22 > 0); } break; case 1: { int w23 = 2; do { p12->f0 = (char)((int)((unsigned)((s9.f0 >> ((s11.f1) & 31)) & ((int)((unsigned)v0 * (unsigned)s10.f0))) << (((((int)((unsigned)s11.f0 * (unsigned)s10.f1)) * ((unsigned long long)s11.f1))) & 31))); } while (--w23 > 0); }  case 2: if (((_Bool)((int)((unsigned char)16)))) { p12->f3 = (unsigned char)(s10.f1 != v3); } else { s9.f1 = (char)s9.f2; }  default: { int i24; for (i24 = 0; i24 < 5; i24++) { v0 = (signed char)((short)((int)((unsigned)s9.f1 - (unsigned)p12->f1)));  s9.f3 = (unsigned char)(((unsigned)(s9.f3 + v5)) * v2); } } } } while (--w21 > 0); }
  p12->f2 = (unsigned long long)(s9.f1 <= p12->f0);
  mixll((unsigned long long)(v5));
  if (((int)((unsigned)(v0 <= v3) + (unsigned)v0))) { { int i25; for (i25 = 0; i25 < 1; i25++) { if (((long)((unsigned long)((int)((unsigned)((char)(-1041056516)) - (unsigned)p12->f3)) * (unsigned long)(((v2) == 0 || ((s9.f0) == (-2147483647L - 1) && (v2) == -1)) ? (long)(s9.f0) : (long)(s9.f0 % v2))))) { v0 = (signed char)((char)s9.f1); } else { p13->f1 = (short)((unsigned)total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4)); }  v3 = (short)p12->f0; } } } else { if (((((p12->f3) == 0 || ((p13->f0) == (-2147483647 - 1) && (p12->f3) == -1)) ? (int)(p13->f0) : (int)(p13->f0 / p12->f3)) * (v4 & v5))) { s10.f1 = (short)((long)((unsigned long)v2 << (((v0 | a8[(unsigned)((v5 + p12->f0)) % 4u])) & 31))); } else { s9.f1 = (char)bump(s9, 2).f0; } }
  if ((v5 - ((int)((unsigned)a8[(unsigned)(p12->f1) % 4u] << ((p13->f0) & 31))))) { a6[(unsigned)(((unsigned)(-727015870))) % 8u] = (char)p12->f2; } else { { int i26; for (i26 = 0; i26 < 5; i26++) { v1 = (unsigned long long)v0;  if (((long)((unsigned long)((unsigned char)(-823778303)) + (unsigned long)((long)((unsigned long)((long)(-299)) - (unsigned long)s10.f0))))) { s9.f2 = (unsigned long long)(((long long)0) ^ (v5 >> ((s9.f1) & 63))); } else { s9.f2 = (unsigned long long)s9.f2; } } } }
  { int w27 = 4; do { if (((unsigned short)(((unsigned)(-250)) > ((unsigned short)(-1176321810))))) { s9 = s9; } else { switch ((unsigned)((s10.f1 ? a7[(unsigned)(((_Bool)p12->f0)) % 5u] : s11.f1)) % 5u) { case 0: p13->f1 = (short)(v4 - ((((unsigned long long)196931104LL * 1499879052LL) ^ v5) ? (p12->f0 * v5) : (((signed char)(-259)) < ((signed char)14)))); break; case 1: a7[(unsigned)(((unsigned short)((signed char)1))) % 5u] = (short)(p12->f0 & ((long long)((unsigned long long)s10.f0 * (unsigned long long)((long long)490283349)))); break; case 2: a7[(unsigned)((s9.f3 & s9.f1)) % 5u] = (short)total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4); break; case 3: v2 = (long)a8[(unsigned)((v5 ? s11.f1 : p13->f1)) % 4u];  default: v3 = (short)s9.f0; } } } while (--w27 > 0); }
  p13->f1 = (short)((total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4) && ((long)((unsigned long)v2 * (unsigned long)p12->f3))) & s11.f0);
  { int i28; for (i28 = 0; i28 < 1; i28++) { s10.f0 = (int)p12->f3;  v2 = (long)((int)((unsigned)a8[(unsigned)((s9.f0 | p12->f1)) % 4u] + (unsigned)(v0 | ((int)(-64))))); } }
  mixll((unsigned long long)(v5));
  { int i29; for (i29 = 0; i29 < 2; i29++) { s11.f1 = (short)p12->f2; if (((p12->f2 ^ s9.f3)) & 1) continue; { int i30; for (i30 = 0; i30 < 2; i30++) { v3 = (short)((short)5); if ((((long long)((unsigned long long)s9.f0 * (unsigned long long)((long long)550646779LL * 855860493LL)))) & 1) continue; switch ((unsigned)((((v3) == 0 || ((((char)(-181))) == (-2147483647 - 1) && (v3) == -1)) ? (int)(((char)(-181))) : (int)(((char)(-181)) % v3))) % 5u) { case 0: p12->f3 = (unsigned char)((unsigned char)(a7[(unsigned)(((unsigned long long)p12->f0)) % 5u] && ((long)(-83)))); break; case 1: v5 = (unsigned long long)v1;  case 2: v2 = (long)total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4);  case 3: v0 = (signed char)(((short)1635334166) ? s11.f1 : p12->f1); break; default: p12->f3 = (unsigned char)((int)((unsigned)(((unsigned long long)12) < bump(s9, 6).f0) - (unsigned)((p12->f2 ^ s10.f0) <= s11.f1))); } } } } }
  p12->f2 = (unsigned long long)(((int)((unsigned)((short)12) - (unsigned)s10.f0)) | ((int)((unsigned)a8[(unsigned)(a6[(unsigned)(s11.f0) % 8u]) % 4u] << ((((unsigned short)(-191))) & 31))));
  v5 = (unsigned long long)(p13->f1 ^ (((long long)(-79)) && ((long)1994884803)));
  v3 = (short)((int)((unsigned)((unsigned char)p13->f1) + (unsigned)(((v0) == 0 || ((a8[(unsigned)((((a6[(unsigned)((v0 < ((long long)402467766))) % 8u]) == 0 || ((s9.f0) == (-2147483647 - 1) && (a6[(unsigned)((v0 < ((long long)402467766))) % 8u]) == -1)) ? (int)(s9.f0) : (int)(s9.f0 / a6[(unsigned)((v0 < ((long long)402467766))) % 8u]))) % 4u]) == (-2147483647 - 1) && (v0) == -1)) ? (int)(a8[(unsigned)((((a6[(unsigned)((v0 < ((long long)402467766))) % 8u]) == 0 || ((s9.f0) == (-2147483647 - 1) && (a6[(unsigned)((v0 < ((long long)402467766))) % 8u]) == -1)) ? (int)(s9.f0) : (int)(s9.f0 / a6[(unsigned)((v0 < ((long long)402467766))) % 8u]))) % 4u]) : (int)(a8[(unsigned)((((a6[(unsigned)((v0 < ((long long)402467766))) % 8u]) == 0 || ((s9.f0) == (-2147483647 - 1) && (a6[(unsigned)((v0 < ((long long)402467766))) % 8u]) == -1)) ? (int)(s9.f0) : (int)(s9.f0 / a6[(unsigned)((v0 < ((long long)402467766))) % 8u]))) % 4u] % v0))));
  p13->f1 = (short)((short)1804131917);
  mix((unsigned)(s11.f1));
  s10 = s11;
  s10 = s11;
  v3 = (short)((s10.f0 | s9.f2) || ((int)((unsigned)a7[(unsigned)(((long long)(-582618580))) % 5u] + (unsigned)a6[(unsigned)(((unsigned long long)p13->f1)) % 8u])));
  v0 = (signed char)s11.f0;
  if (a6[(unsigned)((a7[(unsigned)(((char)3)) % 5u] <= p12->f1)) % 8u]) { { int i31; for (i31 = 0; i31 < 1; i31++) { s9.f3 = (unsigned char)((((unsigned)1) | v3) && a6[(unsigned)((p12->f1 >> ((p12->f1) & 31))) % 8u]);  { int i32; for (i32 = 0; i32 < 4; i32++) { s9.f1 = (char)v1;  v2 = (long)((int)((unsigned)((short)(((signed char)7) | s9.f3)) * (unsigned)s9.f1)); } } } } } else { if ((((int)((unsigned)s10.f0 * (unsigned)a6[(unsigned)(v3) % 8u])) & ((int)((unsigned)a6[(unsigned)(((int)((unsigned)s9.f3 * (unsigned)s10.f1))) % 8u] + (unsigned)s10.f1)))) { switch ((unsigned)((v3 != s9.f0)) % 5u) { case 0: s10.f1 = (short)(p12->f3 | bump(s9, 4).f0); break; case 1: s10.f1 = (short)((((v5 < v1)) == 0 || ((s11.f1) == (-2147483647 - 1) && ((v5 < v1)) == -1)) ? (int)(s11.f1) : (int)(s11.f1 % (v5 < v1))); break; case 2: a6[(unsigned)((p12->f0 & v2)) % 8u] = (char)((short)((int)((unsigned)((int)((unsigned)((char)14) + (unsigned)((signed char)17))) * (unsigned)((short)p12->f1)))); break; case 3: v3 = (short)v5; break; default: s9.f0 = (char)((int)((unsigned)(((a7[(unsigned)((((unsigned char)(-627246224)) ^ s10.f0)) % 5u]) == 0 || ((((unsigned short)14)) == (-2147483647 - 1) && (a7[(unsigned)((((unsigned char)(-627246224)) ^ s10.f0)) % 5u]) == -1)) ? (int)(((unsigned short)14)) : (int)(((unsigned short)14) % a7[(unsigned)((((unsigned char)(-627246224)) ^ s10.f0)) % 5u])) * (unsigned)(p12->f1 <= s11.f1))); } } else { { int i33; for (i33 = 0; i33 < 3; i33++) { v0 = (signed char)((long)((unsigned long)((long)((unsigned long)total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4) + (unsigned long)s10.f0)) + (unsigned long)a6[(unsigned)(v1) % 8u]));  a7[(unsigned)((p12->f0 ^ a8[(unsigned)(((short)v4)) % 4u])) % 5u] = (short)s9.f3; } } } }
  mix((unsigned)(s11.f0));
  v5 = (unsigned long long)s10.f0;
  s11 = s10;
  switch ((unsigned)(((char)p12->f0)) % 5u) { case 0: v1 -= (unsigned long long)(((s10.f0 + v4) * (((((short)57758866)) == 0) ? (unsigned long long)(p12->f2) : (unsigned long long)(p12->f2 % ((short)57758866)))));  case 1: s9.f2 = (unsigned long long)(((((signed char)17) < ((char)(-242))) ^ ((_Bool)p12->f1)) & (((unsigned long long)7) && p12->f3)); break; case 2: p12->f0 = (char)total((const long *)0 == 0 ? (const long *)&tz_[0] : 0, 4); break; default: v4 *= (unsigned)(((s9.f0 | ((int)17)) > (p12->f3 | ((short)11)))); }
  { int i34; for (i34 = 0; i34 < 2; i34++) { v4 = (unsigned)s11.f1; if (((a7[(unsigned)((((long)(-1042017658)) | v3)) % 5u] == a6[(unsigned)((s11.f0 >> ((p12->f1) & 31))) % 8u])) & 1) continue; a7[(unsigned)(p12->f0) % 5u] = (short)s10.f0; } }
  s9.f0 = (char)((v3 >= s9.f2) ^ ((int)((unsigned)p13->f1 * (unsigned)s9.f0)));
  mix((unsigned)(s9.f3));
  mix((unsigned)(v0));
  mixll((unsigned long long)(v1));
  mix((unsigned)(v2));
  mix((unsigned)(v3));
  mix((unsigned)(v4));
  mixll((unsigned long long)(v5));
  { int k_; for (k_ = 0; k_ < 8; k_++) mix((unsigned)(a6[k_])); }
  { int k_; for (k_ = 0; k_ < 5; k_++) mix((unsigned)(a7[k_])); }
  { int k_; for (k_ = 0; k_ < 4; k_++) mix((unsigned)(a8[k_])); }
  mix((unsigned)(s9.f0));
  mix((unsigned)(s9.f1));
  mixll((unsigned long long)(s9.f2));
  mix((unsigned)(s9.f3));
  mix((unsigned)(s10.f0));
  mix((unsigned)(s10.f1));
  mix((unsigned)(s11.f0));
  mix((unsigned)(s11.f1));
  showu("hash", hash_);
  return (int)(hash_ & 0x7f);
}
