/* Generated by scripts/fuzz.mjs --kind=struct (seed 2). */
#include "prelude.h"
struct S0 { unsigned short f0; char f1; int f2; unsigned short f3; };
struct S1 { signed char f0; unsigned f1; int f2; int f3; };
static long a7[8] = { (long)(-68) };
static short a8[8] = { (short)8, (short)10, (short)402399472, (short)(-111), (short)1163518367, (short)171790398 };
static struct S1 s9 = { (-15), 14, (-1334216220), 358442227 };
static struct S1 bump(struct S1 x, int k) { x.f0 += (signed char)k; return x; }
static char total(const char *p, int n) { char s = 0; int i; for (i = 0; i < n; i++) s ^= (char)(p[i] + (char)i); return s; }
static char tz_[4] = { 1, 2, 3, 4 };
int main(void) {
  char v0 = (char)(-148);
  unsigned long long v1 = (unsigned long long)13;
  signed char v2 = (signed char)6;
  int v3 = (int)985342986;
  signed char v4 = (signed char)11;
  unsigned short v5 = (unsigned short)1;
  unsigned a6[3] = { (unsigned)2, (unsigned)906553583, (unsigned)1733106374 };
  struct S0 s10 = { (-250), (-1566507290), (-119), 1066433724 };
  struct S0 s11 = { (-911299618), 14, 17, 2074452825 };
  struct S1 *p12 = &s9;
  struct S0 *p13 = &s10;
  /* bump: struct by value */
  if (((long)((unsigned long)((long)7) - (unsigned long)s9.f0))) { s11.f1 = (char)(((((int)((unsigned)(((p13->f3) == 0 || ((p12->f0) == (-2147483647 - 1) && (p13->f3) == -1)) ? (int)(p12->f0) : (int)(p12->f0 / p13->f3)) - (unsigned)s11.f3))) == 0 || (((((int)((unsigned)s10.f3 << ((((unsigned short)17)) & 31))) & (s9.f3 | p13->f0))) == (-2147483647 - 1) && (((int)((unsigned)(((p13->f3) == 0 || ((p12->f0) == (-2147483647 - 1) && (p13->f3) == -1)) ? (int)(p12->f0) : (int)(p12->f0 / p13->f3)) - (unsigned)s11.f3))) == -1)) ? (int)((((int)((unsigned)s10.f3 << ((((unsigned short)17)) & 31))) & (s9.f3 | p13->f0))) : (int)((((int)((unsigned)s10.f3 << ((((unsigned short)17)) & 31))) & (s9.f3 | p13->f0)) / ((int)((unsigned)(((p13->f3) == 0 || ((p12->f0) == (-2147483647 - 1) && (p13->f3) == -1)) ? (int)(p12->f0) : (int)(p12->f0 / p13->f3)) - (unsigned)s11.f3)))); } else { s9 = s9; }
  s10.f0 = (unsigned short)s11.f1;
  s10.f1 = (char)((signed char)16);
  s10.f0 = (unsigned short)((unsigned char)(v2 == ((long long)(-1510384965))));
  switch ((unsigned)(s9.f2) % 5u) { case 0: v3 = (int)s10.f2; break; case 1: { int i14; for (i14 = 0; i14 < 4; i14++) { if (((p12->f2 ^ ((unsigned)1028176127)) && (((signed char)1340394768) ? s10.f2 : ((unsigned short)(-158))))) { s9.f0 = (signed char)p13->f3; } else { v1 = (unsigned long long)p12->f2; } if (((s9.f3 ? p12->f1 : s9.f2)) & 1) continue; s10.f1 = (char)v0; } }  case 2: p12->f2 = (int)(((v3) == 0 || (((total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4) > v5)) == (-2147483647 - 1) && (v3) == -1)) ? (int)((total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4) > v5)) : (int)((total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4) > v5) % v3)); break; default: { int i15; for (i15 = 0; i15 < 1; i15++) { if (((s10.f1 * a6[(unsigned)(((int)((unsigned)v0 * (unsigned)((int)239634880)))) % 3u]) + v0)) { v5 = (unsigned short)v2; } else { s10.f3 = (unsigned short)bump(s9, 3).f0; }  s9.f1 += (unsigned)(((((p13->f0) == 0 || ((v3) == (-2147483647 - 1) && (p13->f0) == -1)) ? (int)(v3) : (int)(v3 % p13->f0)) >= ((unsigned long long)((unsigned long long)((unsigned long long)(-279)) << ((((char)2)) & 63))))); } } }
  mixll((unsigned long long)(v1));
  { int i16; for (i16 = 0; i16 < 4; i16++) { v3 = (int)((unsigned)((unsigned)(((int)((unsigned)s11.f0 << ((s10.f1) & 31))) ? p12->f3 : p12->f1) << ((((short)(-265))) & 31)));  { int i17; for (i17 = 0; i17 < 3; i17++) { if (((long long)((unsigned long long)((long long)623470256) * (unsigned long long)(p13->f1 == ((char)15))))) { s9.f0 = (signed char)((int)((unsigned)(p12->f1 == p13->f1) + (unsigned)((int)((unsigned)p12->f3 - (unsigned)v0)))); } else { a6[(unsigned)(total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4)) % 3u] = (unsigned)(p12->f3 - ((unsigned)1190652762)); }  s10.f1 = (char)((((s10.f2) == 0 || ((((long long)(-63))) == (-9223372036854775807LL - 1) && (s10.f2) == -1)) ? (long long)(((long long)(-63))) : (long long)(((long long)(-63)) / s10.f2)) | (s9.f1 * p12->f1)); } } } }
  p12->f0 = (signed char)(((s10.f2) == 0 || (((p12->f2 & p12->f3)) == (-2147483647 - 1) && (s10.f2) == -1)) ? (int)((p12->f2 & p12->f3)) : (int)((p12->f2 & p12->f3) % s10.f2));
  a7[(unsigned)((((unsigned short)16) * v1)) % 8u] = (long)((int)((unsigned)(s9.f3 ? p13->f0 : s9.f2) + (unsigned)(((int)(-57)) >= p13->f2)));
  { int i18; for (i18 = 0; i18 < 1; i18++) { { int i19; for (i19 = 0; i19 < 5; i19++) { s11.f0 = (unsigned short)((((((short)482412501) | p12->f1)) == 0) ? (unsigned)((((int)991840726) ? v2 : ((unsigned short)1952356635))) : (unsigned)((((int)991840726) ? v2 : ((unsigned short)1952356635)) / (((short)482412501) | p12->f1)));  s11.f1 = (char)v5; } }  { int i20; for (i20 = 0; i20 < 5; i20++) { v3 = (int)(((((int)((unsigned)v3 + (unsigned)s11.f0))) == 0 || ((((unsigned char)5)) == (-2147483647 - 1) && (((int)((unsigned)v3 + (unsigned)s11.f0))) == -1)) ? (int)(((unsigned char)5)) : (int)(((unsigned char)5) / ((int)((unsigned)v3 + (unsigned)s11.f0))));  s11.f2 = (int)(a8[(unsigned)(((int)((unsigned)v3 + (unsigned)p13->f3))) % 8u] >> (((s10.f2 | s11.f2)) & 31)); } } } }
  { int i21; for (i21 = 0; i21 < 4; i21++) { { int i22; for (i22 = 0; i22 < 5; i22++) { { int i23; for (i23 = 0; i23 < 4; i23++) { s10.f1 = (char)s11.f2;  s9.f1 = (unsigned)(((a8[(unsigned)(((int)((unsigned)p12->f0 - (unsigned)a8[(unsigned)(v2) % 8u]))) % 8u] ^ a8[(unsigned)(total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4)) % 8u]) && ((long long)((char)261441395))) ^ ((long)((unsigned long)((long)(-1992095221)) << (((s9.f0 & ((unsigned short)16))) & 31)))); } } if (((((long)(-707097131)) & s10.f0)) & 1) continue; { int i24; for (i24 = 0; i24 < 4; i24++) { s9.f3 = (int)(((int)((unsigned)((char)(-139)) + (unsigned)((int)(-1585532182)))) & ((_Bool)v1));  s9.f0 = (signed char)((int)((unsigned)((int)((unsigned)(p12->f0 & p13->f3) + (unsigned)total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4))) - (unsigned)((int)((long long)s11.f1)))); } } } }  { int i25; for (i25 = 0; i25 < 3; i25++) { s11.f0 = (unsigned short)v2;  if (((((((int)11)) == 0 || ((v2) == (-2147483647 - 1) && (((int)11)) == -1)) ? (int)(v2) : (int)(v2 / ((int)11))) + ((unsigned long long)a6[(unsigned)(((unsigned)p12->f2)) % 3u]))) { p12->f2 = (int)(((int)p13->f3) & (p13->f3 ? p12->f1 : p12->f2)); } else { s10.f2 = (int)(((((s9.f1 ? s10.f3 : s10.f3) + (((long long)4) - ((unsigned long long)2033431186LL * 1667191154LL)))) == 0) ? (unsigned long long)(((((((long)3)) == 0 || ((p13->f1) == (-2147483647L - 1) && (((long)3)) == -1)) ? (long)(p13->f1) : (long)(p13->f1 / ((long)3))) & (s10.f0 >> ((((long long)(-194))) & 31)))) : (unsigned long long)(((((((long)3)) == 0 || ((p13->f1) == (-2147483647L - 1) && (((long)3)) == -1)) ? (long)(p13->f1) : (long)(p13->f1 / ((long)3))) & (s10.f0 >> ((((long long)(-194))) & 31))) % ((s9.f1 ? s10.f3 : s10.f3) + (((long long)4) - ((unsigned long long)2033431186LL * 1667191154LL))))); } } } } }
  { int k_; for (k_ = 0; k_ < 3; k_++) mix((unsigned)(a6[k_])); }
  { int i26; for (i26 = 0; i26 < 1; i26++) { a6[(unsigned)(s11.f2) % 3u] = (unsigned)a7[(unsigned)(((int)((unsigned)s11.f3 - (unsigned)v5))) % 8u];  s11 = s10; } }
  { int i27; for (i27 = 0; i27 < 5; i27++) { s10.f0 = (unsigned short)((v2 & v0) & (((v0) == 0 || ((p13->f1) == (-2147483647 - 1) && (v0) == -1)) ? (int)(p13->f1) : (int)(p13->f1 % v0)));  p12->f3 = (int)((((s11.f2) == 0 || ((((long)1455557992)) == (-2147483647L - 1) && (s11.f2) == -1)) ? (long)(((long)1455557992)) : (long)(((long)1455557992) % s11.f2)) & s10.f3); } }
  p12->f2 = (int)((((a8[(unsigned)((a7[(unsigned)(((short)p13->f1)) % 8u] != ((short)897728460))) % 8u]) == 0 || ((((short)(-122))) == (-2147483647 - 1) && (a8[(unsigned)((a7[(unsigned)(((short)p13->f1)) % 8u] != ((short)897728460))) % 8u]) == -1)) ? (int)(((short)(-122))) : (int)(((short)(-122)) / a8[(unsigned)((a7[(unsigned)(((short)p13->f1)) % 8u] != ((short)897728460))) % 8u])) < (v5 | p13->f0));
  s11 = s10;
  { int i28; for (i28 = 0; i28 < 3; i28++) { p13->f1 = (char)s10.f0;  s10.f1 = (char)(((long)((long long)1159296062)) < v1); } }
  { int k_; for (k_ = 0; k_ < 8; k_++) mix((unsigned)(a7[k_])); }
  v2 = (signed char)s11.f3;
  { int i29; for (i29 = 0; i29 < 4; i29++) { { int i30; for (i30 = 0; i30 < 5; i30++) { s10.f1 = (char)(((int)((unsigned)v3 * (unsigned)((signed char)(-1863740576)))) | (s11.f2 >= p13->f3)); if ((v0) & 1) continue; s9.f2 = (int)s11.f0; } } if ((bump(s9, 7).f0) & 1) continue; s9.f2 = (int)((long)((unsigned long)((long)(s11.f3 & s11.f3)) * (unsigned long)bump(s9, 0).f0)); } }
  { int i31; for (i31 = 0; i31 < 2; i31++) { if (((v4 != s10.f3) & (((long)0) == v3))) { p13->f2 = (int)((int)((unsigned)((s10.f1 | p12->f0) | ((int)((unsigned)p12->f0 + (unsigned)s11.f1))) << ((bump(s9, 7).f0) & 31))); } else { switch ((unsigned)((s11.f0 == p13->f1)) % 5u) { case 0: v3 = (int)((((s11.f1 ? s10.f0 : s9.f3)) == 0 || ((v3) == (-2147483647 - 1) && ((s11.f1 ? s10.f0 : s9.f3)) == -1)) ? (int)(v3) : (int)(v3 % (s11.f1 ? s10.f0 : s9.f3))); break; case 1: v2 = (signed char)((((long)((unsigned long)s10.f2 + (unsigned long)((long)(-869822522)))) | (((long long)1214263857LL * 182489442LL) ? ((short)1845607310) : s10.f1)) | ((p12->f2 | s11.f1) & a8[(unsigned)(((unsigned char)12)) % 8u])); break; case 2: s11.f0 = (unsigned short)(((int)((unsigned)p13->f2 * (unsigned)s9.f2)) ? ((unsigned)(((a8[(unsigned)(v4) % 8u]) == 0 || ((s9.f3) == (-2147483647 - 1) && (a8[(unsigned)(v4) % 8u]) == -1)) ? (int)(s9.f3) : (int)(s9.f3 % a8[(unsigned)(v4) % 8u]))) : v3);  default: p12->f2 = (int)((int)((unsigned)((int)((unsigned)((short)(-577703331)) << ((s11.f0) & 31))) << (((((s11.f1) == 0 || ((s11.f2) == (-2147483647 - 1) && (s11.f1) == -1)) ? (int)(s11.f2) : (int)(s11.f2 / s11.f1))) & 31))); } } if (((p12->f1 ^ v2)) & 1) continue; p13->f3 = (unsigned short)(s9.f0 ? (((s11.f0) == 0 || ((((unsigned char)11)) == (-2147483647 - 1) && (s11.f0) == -1)) ? (int)(((unsigned char)11)) : (int)(((unsigned char)11) / s11.f0)) : ((s9.f3 ^ ((unsigned)(-34))) == ((int)((unsigned)p12->f2 + (unsigned)((unsigned char)1350771096))))); } }
  v0 = (char)a6[(unsigned)(v4) % 3u];
  p12->f1 = (unsigned)((long long)((unsigned long long)((long long)(-79)) + (unsigned long long)((int)((unsigned)((int)((unsigned)p13->f1 + (unsigned)v5)) * (unsigned)(p13->f3 ^ p13->f3)))));
  mix((unsigned)(v0));
  s10 = s11;
  p12->f1 += (unsigned)(((s10.f0 * ((unsigned)1010707055)) + ((int)((unsigned)p12->f2 << ((s11.f0) & 31)))));
  switch ((unsigned)((v4 | ((long long)1))) % 5u) { case 0: v3 = (int)((p13->f2 && v4) * (((v1) == 0) ? (unsigned long long)(((signed char)13)) : (unsigned long long)(((signed char)13) % v1)));  case 1: if (v3) { p12->f1 = (unsigned)((unsigned long long)1492457043LL * 1037443804LL); } else { { int i32; for (i32 = 0; i32 < 2; i32++) { s9.f3 = (int)(((int)((unsigned)(a8[(unsigned)(a6[(unsigned)(total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4)) % 3u]) % 8u] == p13->f3) * (unsigned)(((unsigned short)12) >> ((s10.f3) & 31)))) & ((p12->f1 ? s11.f1 : a6[(unsigned)((s9.f1 <= p12->f3)) % 3u]) | (s10.f1 | v0)));  p12->f0 = (signed char)v3; } } } break; default: { int i33; for (i33 = 0; i33 < 5; i33++) { a7[(unsigned)(v4) % 8u] = (long)(((unsigned short)(((char)697769586) * ((unsigned)(-14)))) ^ (s11.f2 | (((unsigned long long)(-422004835)) & p12->f0)));  switch ((unsigned)(((int)((unsigned)v0 - (unsigned)((int)(-1535800025))))) % 5u) { case 0: s9.f3 = (int)(((((long)(-182509893)) + s9.f1) == ((int)((unsigned)v5 << ((((short)(-227))) & 31)))) | ((int)((unsigned)(v0 > v2) - (unsigned)(a7[(unsigned)(((int)((unsigned)p12->f3 * (unsigned)p13->f1))) % 8u] ? a8[(unsigned)(((int)((unsigned)s9.f0 * (unsigned)s11.f0))) % 8u] : p13->f3)))); break; case 1: v2 = (signed char)((unsigned long long)663243138LL * 2042348830LL); break; case 2: s9.f2 = (int)((int)bump(s9, 4).f0);  default: a7[(unsigned)((s11.f1 >> ((((int)6)) & 31))) % 8u] = (long)v2; } } } }
  s11.f1 = (char)((int)((unsigned)((int)((unsigned)s9.f2 << ((s9.f2) & 31))) << (((((p12->f3) == 0 || ((p12->f3) == (-2147483647 - 1) && (p12->f3) == -1)) ? (int)(p12->f3) : (int)(p12->f3 / p12->f3))) & 31)));
  v4 = (signed char)(((((int)((unsigned)(p12->f2 ^ s10.f1) << (((p12->f3 - ((unsigned long long)(-1888775887)))) & 31)))) == 0 || ((p13->f0) == (-2147483647 - 1) && (((int)((unsigned)(p12->f2 ^ s10.f1) << (((p12->f3 - ((unsigned long long)(-1888775887)))) & 31)))) == -1)) ? (int)(p13->f0) : (int)(p13->f0 / ((int)((unsigned)(p12->f2 ^ s10.f1) << (((p12->f3 - ((unsigned long long)(-1888775887)))) & 31)))));
  mix((unsigned)(s11.f0));
  s10.f2 = (int)((int)((unsigned)p13->f0 * (unsigned)(p12->f3 >> ((p12->f3) & 31))));
  p13->f2 = (int)(((long long)5) >> ((((int)((unsigned)((unsigned char)v4) * (unsigned)((int)((unsigned)s10.f2 << ((s10.f3) & 31)))))) & 63));
  { int w34 = 2; do { if (total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4)) { { int i35; for (i35 = 0; i35 < 1; i35++) { v5 = (unsigned short)(p12->f2 > s11.f0); if (((s9.f0 | s10.f3)) & 1) continue; s11.f2 = (int)(((bump(s9, 6).f0) == 0 || (((p12->f3 | s11.f2)) == (-2147483647 - 1) && (bump(s9, 6).f0) == -1)) ? (int)((p12->f3 | s11.f2)) : (int)((p12->f3 | s11.f2) % bump(s9, 6).f0)); } } } else { a7[(unsigned)(((char)0)) % 8u] = (long)(p12->f2 != (p13->f3 | v3)); } } while (--w34 > 0); }
  a8[(unsigned)(((long)a8[(unsigned)(((signed char)a6[(unsigned)(((unsigned long long)((signed char)(-250)))) % 3u])) % 8u])) % 8u] = (short)((int)((unsigned)total((const char *)0 == 0 ? (const char *)&tz_[0] : 0, 4) * (unsigned)((int)((unsigned)(p12->f3 < s9.f1) << ((((int)((unsigned)s10.f0 * (unsigned)p13->f0))) & 31)))));
  p12->f0 = (signed char)((unsigned long long)(-181));
  mix((unsigned)(s11.f2));
  { int w36 = 3; do { s9.f0 = (signed char)s11.f1; } while (--w36 > 0); }
  if (((_Bool)v4)) { { int i37; for (i37 = 0; i37 < 4; i37++) { s10.f1 = (char)s9.f3; if (((((a8[(unsigned)(v3) % 8u]) == 0) ? (unsigned long long)(((unsigned long long)1655480676LL * 646008500LL)) : (unsigned long long)(((unsigned long long)1655480676LL * 646008500LL) / a8[(unsigned)(v3) % 8u]))) & 1) continue; p12->f3 = (int)(((s11.f0 & s11.f1) ? (v5 && p13->f2) : ((int)((unsigned)s11.f0 << ((((unsigned long long)1204572605)) & 31)))) - ((((s10.f0) == 0 || ((p13->f3) == (-2147483647 - 1) && (s10.f0) == -1)) ? (int)(p13->f3) : (int)(p13->f3 / s10.f0)) ? (v0 | s9.f3) : v1)); } } } else { v1 ^= (unsigned long long)(p12->f3); }
  a8[(unsigned)(s10.f1) % 8u] = (short)(((((v5 ^ p13->f3)) == 0 || ((((int)((unsigned)s9.f3 + (unsigned)s9.f2))) == (-2147483647 - 1) && ((v5 ^ p13->f3)) == -1)) ? (int)(((int)((unsigned)s9.f3 + (unsigned)s9.f2))) : (int)(((int)((unsigned)s9.f3 + (unsigned)s9.f2)) / (v5 ^ p13->f3))) ? ((int)((unsigned)((int)((unsigned)p12->f2 << ((((unsigned)(-1639687247))) & 31))) + (unsigned)(s9.f0 & s10.f3))) : (p13->f2 >= bump(s9, 1).f0));
  p12->f3 = (int)((int)593886154);
  { int i38; for (i38 = 0; i38 < 1; i38++) { s9 = s9;  { int i39; for (i39 = 0; i39 < 3; i39++) { p12->f3 = (int)s10.f1;  a8[(unsigned)((a8[(unsigned)((((unsigned)(-1860857878)) <= p13->f0)) % 8u] | p13->f0)) % 8u] = (short)p12->f1; } } } }
  mix((unsigned)(s11.f3));
  p13->f0 = (unsigned short)s9.f3;
  mix((unsigned)(v0));
  mixll((unsigned long long)(v1));
  mix((unsigned)(v2));
  mix((unsigned)(v3));
  mix((unsigned)(v4));
  mix((unsigned)(v5));
  { int k_; for (k_ = 0; k_ < 3; k_++) mix((unsigned)(a6[k_])); }
  { int k_; for (k_ = 0; k_ < 8; k_++) mix((unsigned)(a7[k_])); }
  { int k_; for (k_ = 0; k_ < 8; k_++) mix((unsigned)(a8[k_])); }
  mix((unsigned)(s9.f0));
  mix((unsigned)(s9.f1));
  mix((unsigned)(s9.f2));
  mix((unsigned)(s9.f3));
  mix((unsigned)(s10.f0));
  mix((unsigned)(s10.f1));
  mix((unsigned)(s10.f2));
  mix((unsigned)(s10.f3));
  mix((unsigned)(s11.f0));
  mix((unsigned)(s11.f1));
  mix((unsigned)(s11.f2));
  mix((unsigned)(s11.f3));
  showu("hash", hash_);
  return (int)(hash_ & 0x7f);
}
