#!/usr/bin/env node
/* global console */
/**
 * Copies lib/include/*.h and lib/src/* into src/generated.ts as strings, so
 * the browser gets libc without file access. Run after editing lib/:
 *   node packages/libc/scripts/embed.mjs
 * libc.test.ts fails when generated.ts is out of date.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (dir) =>
  readdirSync(join(pkg, dir))
    .sort()
    .map((name) => ({ name, text: readFileSync(join(pkg, dir, name), 'utf8') }));

const headers = read('lib/include');
const sources = read('lib/src');
const out = [
  '// Generated by scripts/embed.mjs from lib/. Do not edit; edit lib/ and rerun.',
  '',
  `export const HEADER_FILES: { name: string; text: string }[] = ${JSON.stringify(headers, null, 2)};`,
  '',
  `export const SOURCE_FILES: { name: string; text: string }[] = ${JSON.stringify(sources, null, 2)};`,
  '',
].join('\n');
const target = join(pkg, 'src/generated.ts');
const config = (await prettier.resolveConfig(target)) ?? {};
writeFileSync(target, await prettier.format(out, { ...config, filepath: target }));
console.log(`src/generated.ts: ${headers.length} headers, ${sources.length} sources`);
